# frozen_string_literal: true

module ErrorCodes
  # 資源相關錯誤
  RECORD_NOT_FOUND = 'RECORD_NOT_FOUND'
  RECORD_INVALID = 'RECORD_INVALID'

  # 認證相關錯誤
  UNAUTHORIZED = 'UNAUTHORIZED'
  FORBIDDEN = 'FORBIDDEN'

  # 驗證相關錯誤
  VALIDATION_ERROR = 'VALIDATION_ERROR'

  # 業務邏輯錯誤
  CHECK_IN_LIMIT_EXCEEDED = 'CHECK_IN_LIMIT_EXCEEDED'
  ACTIVITY_EXPIRED = 'ACTIVITY_EXPIRED'
  INVALID_LOCATION = 'INVALID_LOCATION'

  # 系統錯誤
  SYSTEM_ERROR = 'SYSTEM_ERROR'
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE'
end
